### ISSUE TITLE
Name field in Person is case sensitive

### ISSUE THREAD

**Issue by charlesliyifeng** [AY2425S1-CS2103T-W09-4/tp#134]
When adding a new person with a fully capitalised name (eg. BOB), the fully capitalised name is stored and displayed.
It may be better to convert the name into the correct format first before storing it (eg. Bob).

However, while the stored value is case sensitive, the duplicate handling is not. (BOB is the same as bob)

**Comment by SeanFoongjt** [comment]
To address the first sentence, this is what was intended as it cannot be assumed that the correct format of names are words with one capital letter in the front of each word. This also gives users more freedom to input names and customise as they wish.

For the second sentence, according to our feature specification duplicate handling should be case insensitive.
