### ISSUE TITLE
`find` command does not work for tags with whitespace

### ISSUE THREAD

**Issue by chashaobao123** [AY2425S1-CS2103T-W09-4/tp#207]
Tags with whitespace (in the video example below the tag was "volleyball captain"), searching by 1 word or by the entire tag does not provide the contact in the result

https://github.com/user-attachments/assets/38f13d3e-adfe-4352-bd2b-a96e2fc8b68e

**Comment by lancehaha** [comment]
I'll close this one since using double t/ makes more sense
