### ISSUE TITLE
[PE-D][Tester C] UG does not specify how to add emergency contact

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-4/tp#228]
The edit comand does not display the help format

![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/be0d512a-85e3-4630-ad08-afda1b70f31f.png)

And field constraints does not have any information

![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/f964b06f-e33f-4a6f-b145-60620886d0f3.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: hogretup/ped#1

**Comment by charlesliyifeng** [comment]
duplicate
