### ISSUE TITLE
[PE-D][Tester C] UG does not how to add emergency contact number

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-4/tp#229]
User guide refers to 'field constraints'

![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/44998584-55f4-487b-b929-5c6cf32b3051.png)

But field constraints does not have any information

![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/f964b06f-e33f-4a6f-b145-60620886d0f3.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: hogretup/ped#2

**Comment by charlesliyifeng** [comment]
duplicate
