### ISSUE TITLE
[PE-D][Tester C] When importing invalid characters, the application does not show any errors

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-4/tp#254]
When directly modifying stoage json to use chinese, 

![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/33743ea7-16c8-47db-a706-692502c31129.png)

When booting the application, the application is unable to load any data

![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/073b2da2-ce3f-4a8b-832d-fdd781d6d4cf.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: hogretup/ped#9

**Comment by SeanFoongjt** [comment]
May I check if you raised this as an error for the base reading on opening the application or whether this bug is meant for the `import` feature that was implemented separately?
