### ISSUE TITLE
[PE-D][Tester C] When modifying data.json to have multiple same phone numbers, application is unable to load

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W09-4/tp#258]
![image.png](https://raw.githubusercontent.com/hogretup/ped/main/files/623b6420-c36f-42ce-86a6-63a86750d9be.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: hogretup/ped#10

**Comment by SeanFoongjt** [comment]
Not in scope, explained in User Guide under editing the save file.
